export const SET_CURRENT_USER = "SET_CURRENT_USER"
export const SET_CURRENT_USER_SUCCESS = "SET_CURRENT_USER_SUCCESS"
export const SET_CURRENT_USER_FAIL = "SET_CURRENT_USER_FAIL"
export const UPDATE_COOKIE_STORE = "UPDATE_COOKIE_STORE"
export const GET_AVAILABLE_SHIFTS = "GET_AVAILABLE_SHIFTS";
export const GET_AVAILABLE_SHIFTS_SUCCESS = "GET_AVAILABLE_SHIFTS_SUCCESS";
export const GET_USER_DATA_BEGIN = "GET_USER_DATA_BEGIN";
export const GET_USER_DATA_SUCCESS = "GET_USER_DATA_SUCCESS";
export const SAVE_USER_SHIFTS = "SAVE_USER_SHIFTS";
export const SAVE_USER_SHIFTS_IN_RANGE = "SAVE_USER_SHIFTS_IN_RANGE";
export const GET_ALL_USERS = "GET_ALL_USERS";
export const GET_ALL_USERS_SUCCESS = "GET_ALL_USERS_SUCCESS";
export const GET_ALL_SHIFTS_FOR_DATE = "GET_ALL_SHIFTS_FOR_DATE";
export const GET_ALL_SHIFTS_FOR_DATE_SUCCESS = "GET_ALL_SHIFTS_FOR_DATE_SUCCESS";
export const GET_ALL_SHIFTS_FOR_MONTH = "GET_ALL_SHIFTS_FOR_MONTH";
export const GET_ALL_SHIFTS_FOR_MONTH_SUCCESS = "GET_ALL_SHIFTS_FOR_MONTH_SUCCESS";
export const SAVE_USER = "SAVE_USER";
export const SAVE_USER_SUCCESS = "SAVE_USER_SUCCESS"
export const SAVE_USER_IS_ADMIN = "SAVE_USER_IS_ADMIN";
export const SAVE_USER_BATCH = "SAVE_USER_BATCH";
export const SAVE_USER_BATCH_SUCCESS = "SAVE_USER_BATCH_SUCCESS";
export const SAVE_USER_IS_ADMIN_SUCCESS = "SAVE_USER_IS_ADMIN_SUCCESS";
export const DELETE_USERS = "DELETE_USERS";
export const DELETE_USERS_SUCCESS = "DELETE_USERS_SUCCESS";



