export const SET_CURRENT_USER = "SET_CURRENT_USER"
export const SET_CURRENT_USER_SUCCESS = "SET_CURRENT_USER_SUCCESS"
export const UPDATE_COOKIE_STORE = "UPDATE_COOKIE_STORE"
export const GET_USER_DATA_BEGIN = "GET_USER_DATA_BEGIN";
export const GET_USER_DATA_SUCCESS = "GET_USER_DATA_SUCCESS";
export const SAVE_USER_SHIFTS = "SAVE_USER_SHIFTS";
