export const SET_CURRENT_USER = "SET_CURRENT_USER"
export const SET_CURRENT_USER_SUCCESS = "SET_CURRENT_USER_SUCCESS"
export const UPDATE_COOKIE_STORE = "UPDATE_COOKIE_STORE"
export const GET_USER_DATA_BEGIN = "GET_USER_DATA_BEGIN";
export const GET_USER_DATA_SUCCESS = "GET_USER_DATA_SUCCESS";
export const SAVE_USER_SHIFTS = "SAVE_USER_SHIFTS";
export const GET_ALL_USERS = "GET_ALL_USERS";
export const GET_ALL_USERS_SUCCESS = "GET_ALL_USERS_SUCCESS";
export const GET_ALL_SHIFTS_FOR_DATE = "GET_ALL_SHIFTS_FOR_DATE";
export const GET_ALL_SHIFTS_FOR_DATE_SUCCESS = "GET_ALL_SHIFTS_FOR_DATE_SUCCESS";
export const SAVE_USER_IS_ADMIN = "SAVE_USER_IS_ADMIN";
export const SAVE_USER_IS_ADMIN_SUCCESS = "SAVE_USER_IS_ADMIN_SUCCESS";

